# -*- coding: utf-8 -*-
"""Sign-Lan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18BbM3-0_VVn2FTuBs-uXlHv4BzsXhgw7
"""

import os
import torch
import torch.nn as nn
import pandas as pd
from torch.optim import Adam
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms.v2 as transforms
import torchvision.transforms.functional as F

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device configured: {device}")

train_path = "data/asl_data/sign_mnist_train.csv"
valid_path = "data/asl_data/sign_mnist_valid.csv"

IMG_HEIGHT = 28
IMG_WIDTH = 28
IMG_CHS = 1
N_CLASSES = 24

train_df = pd.read_csv(train_path)
valid_df = pd.read_csv(valid_path)

class MyDataset(Dataset):
    def __init__(self, base_df):
        x_df = base_df.copy()
        y_df = x_df.pop('label')

        y_df = y_df.apply(lambda label: label - 1 if label > 8 else label)
        y_df = y_df.apply(lambda label: label - 1 if label > 24 else label)

        x_df = x_df.values / 255.0
        x_df = x_df.reshape(-1, IMG_CHS, IMG_WIDTH, IMG_HEIGHT)

        self.xs = torch.tensor(x_df).float().to(device)
        self.ys = torch.tensor(y_df).to(device)

    def __getitem__(self, idx):
        return self.xs[idx], self.ys[idx]

    def __len__(self):
        return len(self.xs)

batch_size = 32
train_loader = DataLoader(MyDataset(train_df), batch_size=batch_size, shuffle=True)
train_N = len(train_loader.dataset)

valid_loader = DataLoader(MyDataset(valid_df), batch_size=batch_size, shuffle=False)
valid_N = len(valid_loader.dataset)

class MyConvBlock(nn.Module):
    def __init__(self, in_ch, out_ch, dropout_p):
        kernel_size = 3
        super().__init__()

        self.model = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, kernel_size, stride=1, padding=1),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(),
            nn.Dropout(dropout_p),
            nn.MaxPool2d(2, stride=2)
        )

    def forward(self, x):
        return self.model(x)

flattened_img_size = 75 * 3 * 3

base_model = nn.Sequential(
    MyConvBlock(IMG_CHS, 25, 0),
    MyConvBlock(25, 50, 0.2),
    MyConvBlock(50, 75, 0),

    nn.Flatten(),
    nn.Linear(flattened_img_size, 512),
    nn.Dropout(0.3),
    nn.ReLU(),
    nn.Linear(512, N_CLASSES)
)

model = torch.compile(base_model.to(device))
loss_function = nn.CrossEntropyLoss()
optimizer = Adam(model.parameters())

random_transforms = transforms.Compose([
    transforms.RandomRotation(5),
    transforms.RandomResizedCrop((IMG_WIDTH, IMG_HEIGHT), scale=(0.9, 1), ratio=(1, 1)),
    transforms.RandomHorizontalFlip(),
    transforms.ColorJitter(brightness=0.2, contrast=0.5)
])

def get_batch_accuracy(output, y, N):
    pred = output.argmax(dim=1, keepdim=True)
    correct = pred.eq(y.view_as(pred)).sum().item()
    return correct / N

def train_step():
    total_loss, total_accuracy = 0, 0
    model.train()

    for x, y in train_loader:
        augmented_x = random_transforms(x)

        output = model(augmented_x)
        optimizer.zero_grad()
        batch_loss = loss_function(output, y)
        batch_loss.backward()
        optimizer.step()

        total_loss += batch_loss.item()
        total_accuracy += get_batch_accuracy(output, y, train_N)

    print('Train - Loss: {:.4f} Accuracy: {:.4f}'.format(total_loss, total_accuracy))

def validate_step():
    total_loss, total_accuracy = 0, 0
    model.eval()

    with torch.no_grad():
        for x, y in valid_loader:
            output = model(x)
            total_loss += loss_function(output, y).item()
            total_accuracy += get_batch_accuracy(output, y, valid_N)

    print('Valid - Loss: {:.4f} Accuracy: {:.4f}'.format(total_loss, total_accuracy))

print("\n--- Starting The Ultimate Combined Sign Language Training ---")
epochs = 20

for epoch in range(epochs):
    print(f'Epoch: {epoch}/{epochs-1}')
    train_step()
    validate_step()

torch.save(base_model, 'ultimate_asl_model.pth')
print("--- SUCCESS! Training finished & Model saved as 'ultimate_asl_model.pth' ---")